
  # After registering a name on build.snapcraft.io, commit an uncommented line:
  name: cryptobit
  version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
  summary: Single-line elevator pitch for your amazing snap # 79 char long summary
  description: |
    Bitcoinrand Core version v1.0.0.0-g (32-bit) Copyright (C) 2020 The Bitcoinrand Core developers Copyright (C) 2009-2020 The Bitcoin Core developers Please contribute if you find Bitcoinrand Core useful. Visit https://bitcoinrand.com for further information about the software.
  grade: devel # must be 'stable' to release into candidate/stable channels
  confinement: devmode # use 'strict' once you have the right plugs and slots

  parts:
    my-part:
      # See 'snapcraft plugins'
      plugin: nil
  
